import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });

// P1.5 (BUILD-PLAN.md): non-interactive flat config, originally so `next lint`
// ran in CI instead of hitting the setup prompt. K13a swapped the script to
// the `eslint .` CLI (`next lint` is deprecated in 15.5, gone in 16), which
// lints by directory walk rather than by Next's fixed directory list — so the
// ignores below now have to name the generated files Next used to skip for us.
const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      // Generated by `next build`, git-ignored, and not ours to style: 15.5
      // writes a triple-slash reference to ./.next/types/routes.d.ts into it,
      // which `@typescript-eslint/triple-slash-reference` rejects.
      "next-env.d.ts",
      "out/**",
      "public/sw.js",
      "public/swe-worker-*.js",
      "playwright-report/**",
      "test-results/**",
    ],
  },
];

export default eslintConfig;
